---
version: 2
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  builder: "dirhtml"
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow
      - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
      - git fetch --all --tags
